frontend_test:
  stage: test
  image: python:3.9
  services:
    - name: selenium/standalone-edge:latest
      alias: selenium
  before_script:
    - pip install robotframework selenium robotframework-seleniumlibrary
  script:
    - cd test
    - python -m webdriver_manager.microsoft --install
    - export DISPLAY=:99
    - export EDGE_BIN=/usr/bin/microsoft-edge
    - export EDGE_DRIVER=/usr/bin/msedgedriver
    - robot --outputdir=results usuario.robot
