stages:
  - test

# Job para executar testes do Robot Framework para o usuário
usuario_test:
  stage: test
  image: python:3.9
  services:
    - selenium/standalone-chrome
  variables:
    BASE_URL: http://localhost:9000  # Se necessário, altere para a URL do seu projeto
  before_script:
    # Instalar dependências necessárias para o Selenium funcionar corretamente
    - apt-get update && apt-get install -y chromium chromium-driver
    - pip install --upgrade pip
    - pip install robotframework
    - pip install robotframework-seleniumlibrary
    - pip install selenium
    - pip install webdriver-manager
    - python -m webdriver_manager.chrome --install
  script:
    # Executa os testes Robot Framework
    - robot --outputdir=results usuario.robot
  artifacts:
    paths:
      - results/
    when: always
